apiVersion: dataplane.openstack.org/v1beta1
kind: OpenStackDataPlaneDeployment
metadata:
  name: ovn-update
  namespace: openstack
spec:
  nodeSets:
    - openstack-edpm-ipam
  servicesOverride:
    - ovn-update
