k9s:
  cluster: api-slagle-upshift-localdomain:6443
  namespace:
    active: fraud-detection
    lockFavorites: false
    favorites:
    - openshift-image-registry
    - fraud-detection
    - default
  view:
    active: configmap
  featureGates:
    nodeShell: false
  portForwardAddress: localhost
